pattern_cols: 12
pattern_rows: 9
center_distance_mm: 20

R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]
camera_matrix: [1,0,0,0,1,0,0,0,1]
distort_coeffs: [0,0,0,0,0]


camera_name: "hikrobot"
exposure_ms: 30
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----uart参数-----#####
com_port: "/dev/ttyACM0"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0